version: "3.8"

services:
  api:
    image: leandrobertoluzzi/cnc-api:latest
    #build:
    #  context: .
    #  target: production
    ports:
      - "8000:80"
    restart: always

  postgresql:
    restart: always

  ngrok:
    restart: always
    command: http --domain=${NGROK_DOMAIN} api:80 --scheme http,https
    environment:
      - NGROK_DOMAIN=${NGROK_DOMAIN}
