version: "3.8"

services:
  mysql:
    container_name: remote-cnc-api-mysql
    image: mysql:5.7
    networks:
      - backend
    env_file:
      - mysql/.env
    volumes:
      - mysql-datavolume:/var/lib/mysql

  phpmyadmin:
    container_name: remote-cnc-api-phpmyadmin
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=remote-cnc-api-mysql
      - PMA_PORT=3306
    volumes:
      - /sessions

networks:
  backend:

volumes:
  mysql-datavolume:
