version: "3.8"

services:
  api:
    build:
      context: ./
      target: production
    restart: always

  postgresql:
    restart: always

  ngrok:
    restart: always
    command: http --domain=${NGROK_DOMAIN} api:8000 --scheme http,https
    environment:
      - NGROK_DOMAIN=${NGROK_DOMAIN}
